# Generated by Django 2.2.16 on 2021-11-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'Комментарий автора', 'verbose_name_plural': 'Комментарии авторов'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Комментарий к посту', verbose_name='Комментарий'),
        ),
    ]
