# Generated by Django 2.2.16 on 2021-11-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20211106_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
